version: '3.9'
services:
  backend:
    build:
      context: backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    stop_signal: SIGINT
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend-db
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_DB=db

  database:
    image: mysql
    ports:
      - '3306:3306'
    secrets:
      - db-password
      - db-root-password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$(cat /run/secrets/db-root-password)"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-db

volumes:
  db-data:

secrets:
  db-password:
    file: userDatabase/password.txt
  db-root-password:
    file: userDatabase/root_password.txt

networks:
  backend-db:
